routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/* Web */
Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/search', 'HomeController@search')->name('home.search');


/* Front */ 
Route::namespace('Front')->group(function () {
    Route::get('front/login','LoginController@login')->name('front.login');
    Route::post('front/logindata','LoginController@logindata')->name('front.logindata');
    Route::get('front/logout','LoginController@logout')->name('front.logout');
    Route::get('front/profile','ProfileController@create')->name('front.profile');
    Route::get('front/create','RegisterController@create')->name('front.create');
    Route::post('front/store','RegisterController@store')->name('front.store');
	Route::get('/digital-directory', 'DigitalDirectoryController@index')->name('front.digitaldirectory');
	Route::get('/product/{id}', 'ProductController@index')->name('front.product_details');
    Route::get('/wine-importers-in-usa', 'DigitalDirectoryController@WineUsa')->name('front.wine_imports_usa');
    Route::get('/product-description/{id}','ProductController@view')->name('front.product_description');
    Route::get('/news-details/{id}','ProductController@newsDetail')->name('front.news_details');
    Route::get('/event-details/{id}','ProductController@eventDetail')->name('front.event_details');
    Route::get('/wine-importer-detail/{id}','DigitalDirectoryController@wineDetail')->name('front.wine_importer_details');
});
/* Buyer */

/* Seller */

/* Admin */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::namespace('Customers')->group(function () {
        	Route::resource('customers', 'CustomerController');
            Route::post('is_active/{id}','CustomerController@isActive')->name('customers.is_active');
       	});
		Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
        Route::namespace('Categories')->group(function () {
            Route::resource('categories', 'CategoryController');
            Route::get('categories/subcat/{id}','CategoryController@getSubcategory')->name('getsubcat');
        });
        Route::namespace('News')->group(function () {
            Route::get('news','NewsController@create')->name('news.create');
            Route::post('news-store','NewsController@store')->name('news.store');
            Route::get('news-list','NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','NewsController@edit')->name('news.edit');
            Route::post('news/status/{id}', 'NewsController@status')->name('news.status');
        });
        Route::namespace('Events')->group(function () {
            Route::get('events','EventsController@create')->name('events.create');
            Route::post('events-store','EventsController@store')->name('events.store');
            Route::get('events-list','EventsController@index')->name('events.list');
            Route::get('events/delete/{id}','EventsController@destroy')->name('events.destroy'); 
            Route::get('events/edit/{id}','EventsController@edit')->name('events.edit');
            Route::post('events/status/{id}', 'EventsController@status')->name('events.status');
        });
        Route::namespace('DigitalDirectory')->group(function () {
            Route::get('digitaldirectory','DigitalDirectoryController@create')->name('digitaldirectory.create');
            Route::post('digitaldirectory-store','DigitalDirectoryController@store')->name('digitaldirectory.store');
            Route::get('digitaldirectory-list','DigitalDirectoryController@index')->name('digitaldirectory.list');
            Route::get('digitaldirectory/delete/{id}','DigitalDirectoryController@destroy')->name('digitaldirectory.destroy'); 
            Route::get('digitaldirectory/edit/{id}','DigitalDirectoryController@edit')->name('digitaldirectory.edit');
            Route::post('digitaldirectory/status/{id}', 'DigitalDirectoryController@status')->name('digitaldirectory.status');
            Route::get('digitaldirectory/subcat/{id}','DigitalDirectoryController@getSubdigicategory')->name('getsubcatdigital');
            // None Listed Consultan
            Route::get('digitaldirectoryconsultant/list','ConsultantController@index')->name('digitaldirectory.none_listed_consultant');
            Route::get('digitaldirectoryconsultant/create','ConsultantController@create')->name('digitaldirectory.none_listed_consultant_create');
            Route::post('digitaldirectoryconsultant-store','ConsultantController@store')->name('digitaldirectory.none_listed_consultant_store');
            Route::get('digitaldirectoryconsultant/delete/{id}','ConsultantController@destroy')->name('digitaldirectory.none_listed_consultant_destroy'); 
            Route::get('digitaldirectoryconsultant/edit/{id}','ConsultantController@edit')->name('digitaldirectory.none_listed_consultant_edit');
            Route::post('digitaldirectoryconsultant/status/{id}', 'ConsultantController@status')->name('digitaldirectory.none_listed_consultant_status');
        });
        Route::namespace('Academys')->group(function(){
            // Author
            Route::get('author/list','AuthorController@index')->name('academys.list_author');
            Route::get('author/create','AuthorController@create')->name('academys.create_author');
            Route::get('author/edit/{id}','AuthorController@edit')->name('academys.edit_author');
            Route::get('author/delete/{id}','AuthorController@destroy')->name('academys.destroy_author');
            Route::post('author/store','AuthorController@store')->name('academys.store_author');
            //Route::post('academystore','AcademyController@create');

            //Contents
            Route::get('content/list','ContentController@index')->name('academys.list_content');
            Route::get('content/create','ContentController@create')->name('academys.create_content');
            Route::get('content/delete/{id}','ContentController@destroy')->name('academys.destroy_content');
            Route::get('content/edit/{id}','ContentController@edit')->name('academys.edit_content');
            Route::post('content/store','ContentController@store')->name('academys.store_content');

            //Webinar
            Route::get('webinar/list','WebinarController@index')->name('academys.list_webinar');
            Route::get('webinar/create','WebinarController@create')->name('academys.create_webinar');
            Route::get('webinar/edit/{id}','WebinarController@edit')->name('academys.edit_webinar');
            Route::get('webinar/delete/{id}','WebinarController@destroy')->name('academys.destroy_webinar');
            Route::post('webinar/store','WebinarController@store')->name('academys.store_webinar');

            //Articles
            Route::get('article/list','ArticleController@index')->name('academys.list_article');
            Route::get('article/create','ArticleController@create')->name('academys.create_article');
             Route::get('article/edit/{id}','ArticleController@edit')->name('academys.edit_article');
            Route::get('article/delete/{id}','ArticleController@destroy')->name('academys.destroy_article');
            Route::post('article/store','ArticleController@store')->name('academys.store_article');
        });
	});
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/Customers/CustomerAddressController.php
<?php

namespace App\Http\Controllers\Admin\Customers;

use App\Shop\Addresses\Repositories\Interfaces\AddressRepositoryInterface;
use App\Shop\Countries\Repositories\Interfaces\CountryRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Shop\Provinces\Repositories\Interfaces\ProvinceRepositoryInterface;

class CustomerAddressController extends Controller
{
    /**
     * @var AddressRepositoryInterface
     */
    private $addressRepo;
    /**
     * @var CountryRepositoryInterface
     */
    private $countryRepo;
    /**
     * @var ProvinceRepositoryInterface
     */
    private $provinceRepo;

    /**
     * CustomerAddressController constructor.
     * @param AddressRepositoryInterface $addressRepository
     * @param CountryRepositoryInterface $countryRepository
     * @param ProvinceRepositoryInterface $provinceRepository
     */
    public function __construct(
        AddressRepositoryInterface $addressRepository,
        CountryRepositoryInterface $countryRepository,
        ProvinceRepositoryInterface $provinceRepository
    ) {
        $this->addressRepo = $addressRepository;
        $this->countryRepo = $countryRepository;
        $this->provinceRepo = $provinceRepository;
    }

    /**
     * Show the customer's address
     *
     * @param int $customerId
     * @param int $addressId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(int $customerId, int $addressId)
    {
        return view('admin.addresses.customers.show', [
            'address' => $this->addressRepo->findAddressById($addressId),
            'customerId' => $customerId
        ]);
    }

    /**
     * Show the edit form
     *
     * @param int $customerId
     * @param int $addressId
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(int $customerId, int $addressId)
    {
        $this->countryRepo->findCountryById(env('COUNTRY_ID', 1));
        $province = $this->provinceRepo->findProvinceById(1);

        return view('admin.addresses.customers.edit', [
            'address' => $this->addressRepo->findAddressById($addressId),
            'countries' => $this->countryRepo->listCountries(),
            'provinces' => $this->countryRepo->findProvinces(),
            'cities' => $this->provinceRepo->listCities($province->id),
            'customerId' => $customerId
        ]);
    }
}

resources/views/admin/customers/create.blade.php
@extends('layouts.admin.layout')
@section('content')
    <div class="container-fluid">
        <div class="row bg-title">
            <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                <h4 class="page-title">Create User</h4> 
            </div>
        </div>
        <div class="page-content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="product-tab">
                        <ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
                            @if(isset($customer->id))
                                <li class="active"><a>Edit User</a></li>
                            @else
                                <li class="active"><a>Add User</a></li>
                            @endif
                            <li><a href="{{ route('admin.customers.index') }}">User Listing</a></li>
                        </ul>
                        <div class="tab-content">
                            <div id="AddProcucts" class="tab-pane fade in active">
                                <div class="add-product">
                                <!-- Main content -->
                                    <section class="content">
                                        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
                                            <div class="box">
                                                <form action="{{ route('admin.customers.store') }}" method="post" class="form">
                                                    <input type="hidden" name="id" value="@if(isset($customer->id)){{ $customer->id }}@elseif(old('id')!=''){{ old('id') }} @endif" maxlength="50">
                                                    <div class="box-body">
                                                        {{ csrf_field() }}
                                                        <div class="form-group">
                                                            <label for="username">Username <span class="text-danger">*</span></label>
                                                            <input type="text" name="username" id="username" placeholder="Username" class="form-control" value="@if(isset($customer->username)){{ $customer->username }}@elseif(old('username')!=''){{ old('username') }} @endif">
                                                            @if($errors->has('username'))
                                                                <span class="text-danger">{{$errors->first('username')}}</span>
                                                            @endif
                                                        </div>
                                                        @if(isset($customer->id))
                                                        <div class="form-group">
                                                            <label>Create New Password</label>
                                                            <input type="password" name="new_password" id="new_password" class="form-control" placeholder="****" maxlength="15">
                                                            @if($errors->has('password'))
                                                                <span class="text-danger">{{$errors->first('password')}}</span>
                                                            @endif
                                                        </div>
                                                        @else
                                                        <div class="form-group">
                                                            <label for="password">Password <span class="text-danger">*</span></label>
                                                            <input type="password" name="password" id="password" placeholder="xxxxx" class="form-control" maxlength="15">
                                                            @if($errors->has('password'))
                                                                <span class="text-danger">{{$errors->first('password')}}</span>
                                                            @endif
                                                        </div>
                                                        @endif
                                                        <div class="form-group">
                                                            <label for="name">Name <span class="text-danger">*</span></label>
                                                            <input type="text" name="name" id="name" placeholder="Name" class="form-control" value="@if(isset($customer->name)){{ $customer->name }}@elseif(old('name')!=''){{ old('name') }} @endif" maxlength="100">
                                                            @if($errors->has('name'))
                                                                <span class="text-danger">{{$errors->first('name')}}</span>
                                                            @endif
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="surname">Surname <span class="text-danger">*</span></label>
                                                            <input type="text" name="surname" id="surname" placeholder="Surname" class="form-control" value="@if(isset($customer->surname)){{ $customer->surname }}@elseif(old('surname')!=''){{ old('surname') }} @endif" maxlength="50">
                                                            @if($errors->has('surname'))
                                                                <span class="text-danger">{{$errors->first('surname')}}</span>
                                                            @endif
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="country">Address Country: <span class="text-danger">*</span></label>
                                                            <select name="country" class="form-control">
                                                                <option value="">Select Country</option>
                                                                @foreach ($countrys as $country)
                                                                <option value="{{ $country->id }}"
                                                                @if(old('country')==$country->id) selected="true"
                                                                @elseif(isset($customer->country) && $customer->country==$country->id)
                                                                selected="true"
                                                                @endif>{{ $country->country }}</option>
                                                                @endforeach
                                                            </select>
                                                            @if($errors->has('country'))
                                                                <span class="text-danger">{{$errors->first('country')}}</span>
                                                            @endif
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="surname">Landline <span class="text-danger">*</span></label>
                                                            <input type="text" name="phone" id="number" placeholder="Landline Number" maxlength="15" class="form-control number" value="@if(isset($customer->phone)){{ $customer->phone }}@elseif(old('phone')!=''){{ old('phone') }} @endif">
                                                            @if($errors->has('phone'))
                                                                <span class="text-danger">{{$errors->first('phone')}}</span>
                                                            @endif
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="email">Email <span class="text-danger">*</span></label>
                                                            <div class="input-group">
                                                                <span class="input-group-addon">@</span>
                                                                <input type="text" name="email" id="email" placeholder="Email" maxlength="50" class="form-control" value="@if(isset($customer->email)){{ $customer->email }}@elseif(old('email')!=''){{ old('email') }} @endif">
                                                            </div>
                                                            @if($errors->has('email'))
                                                                <span class="text-danger">{{$errors->first('email')}}</span>
                                                            @endif
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="email">Comments/ Remarks<span class="text-danger"></span></label>
                                                            <textarea name="comments" maxlength="500" class="form-control">@if(isset($customer->comments)){{ $customer->comments }}@elseif(old('comments')!=''){{ old('comments') }} @endif</textarea>
                                                           <!--  @if($errors->has('comments'))
                                                                <span class="text-danger">{{$errors->first('comments')}}</span>
                                                            @endif -->
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="status">Status </label>
                                                            <select name="status" id="status" class="form-control">
                                                                <option value="0"   @if(old('status')=="0") selected="true" @elseif(isset($customer->status) && $customer->status==0)selected="true"@endif>Disable</option>
                                                                <option value="1"
                                                                   @if(old('status')=="1") selected="true" @elseif(isset($customer->status) && $customer->status==1)selected="true"@endif>Enable</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <!-- /.box-body -->
                                                    <div class="box-footer">
                                                        <div class="btn-group">
                                                            <a href="{{ route('admin.dashboard') }}" class="btn btn-default">Back</a>
                                                            @if(isset($customer->id))
                                                            <button type="submit" class="btn btn-primary">Update</button>
                                                            @else
                                                            <button type="submit" class="btn btn-primary">Create</button>
                                                            @endif
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </section>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('js')
<script type="text/javascript" src="{{url('js/custom/custom.js')}}"></script>
@endpush

resources/views/admin/customers/list.blade.php
@extends('layouts.admin.layout')
@section('content')
<div class="container-fluid">
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Manage User</h4>
        </div>
    </div>
    @include('layouts.errors-and-messages')
    <div class="page-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="customer-tab">                          
                    <ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
    					<li class="active"><a  href="{{route('admin.customers.index')}}">User Listing</a></li>
    					<li><a href="{{route('admin.customers.create')}}">User Create </a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="ProductListing" class="tab-pane fade in active">
                            <div class="product-listing">
                                <div class="table-responsive">
                                <table  class="table border-b1px customers" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>E-mail</th>
                                        <th>Country</th>
                                        <th>Phone</th>
                                        <th>Status</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @forelse ($customers as  $customer)
                                        <tr>
                                            <td>{{ $customer->name}}</td>
                                            <td>{{ $customer->email }}</td>
                                            <td>{{ $customer->country_name }}</td>
                                            <td>{{ $customer->phone }}</td>
                                            <td>
                                            <form action="{{route('admin.customers.is_active',$customer->id)}}" method="post" class="form-horizontal">
                                                {{ csrf_field() }}
                                                @if($customer->status == "1")
                                                    <button class="btn in-active-status" onclick="return confirm('Are you sure? You want to change status.')">Active</button>
                                                @else
                                                    <button class="btn in-active-status" onclick="return confirm('Are you sure? You want to change status.')">InActive</button>
                                                @endif
                                            </form>
                                            </td>
                                            <td>
                                                <div class="action-btn">
                                                    <form action="{{ route('admin.customers.destroy', $customer->id) }}" method="post" class="form-horizontal">
                                                        {{ csrf_field() }}
                                                        <input type="hidden" name="_method" value="delete">
                                                        <div class="btn-group">
                                                            <a href="{{ route('admin.customers.edit', $customer->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
                                                            <button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="10" align="center">Data Not Found</td>
                                        </tr>
                                    @endforelse
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<style type="text/css">
    .search{
        float: right!important;
        padding-bottom: 10px;
    }
    .btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@push('js')
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script>
    $(document).ready(function() {
        init_datatable();
    } );
    
    function init_datatable(){
        $('.customers').DataTable().destroy();
        setTimeout(function(){
            var table = $('.customers').DataTable({
                deferRender: true,
                scrollX: true
            });
        },300);
    }
</script>
@endpush