routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/* Web */
Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/search', 'HomeController@search')->name('home.search');


/* Front */ 
Route::namespace('Front')->group(function () {
    Route::get('front/login','LoginController@login')->name('front.login');
    Route::post('front/logindata','LoginController@logindata')->name('front.logindata');
    Route::get('front/logout','LoginController@logout')->name('front.logout');
    Route::get('front/profile','ProfileController@create')->name('front.profile');
    Route::get('front/create','RegisterController@create')->name('front.create');
    Route::post('front/store','RegisterController@store')->name('front.store');
	Route::get('/digital-directory', 'DigitalDirectoryController@index')->name('front.digitaldirectory');
	Route::get('/product/{id}', 'ProductController@index')->name('front.product_details');
    Route::get('/wine-importers-in-usa', 'DigitalDirectoryController@WineUsa')->name('front.wine_imports_usa');
    Route::get('/product-description/{id}','ProductController@view')->name('front.product_description');
    Route::get('/news-details/{id}','ProductController@newsDetail')->name('front.news_details');
    Route::get('/event-details/{id}','ProductController@eventDetail')->name('front.event_details');
    Route::get('/wine-importer-detail/{id}','DigitalDirectoryController@wineDetail')->name('front.wine_importer_details');
});
/* Buyer */

/* Seller */

/* Admin */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::namespace('Customers')->group(function () {
        	Route::resource('customers', 'CustomerController');
            Route::post('is_active/{id}','CustomerController@isActive')->name('customers.is_active');
       	});
		Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
        Route::namespace('Categories')->group(function () {
            Route::resource('categories', 'CategoryController');
            Route::get('categories/subcat/{id}','CategoryController@getSubcategory')->name('getsubcat');
        });
        Route::namespace('News')->group(function () {
            Route::get('news','NewsController@create')->name('news.create');
            Route::post('news-store','NewsController@store')->name('news.store');
            Route::get('news-list','NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','NewsController@edit')->name('news.edit');
            Route::post('news/status/{id}', 'NewsController@status')->name('news.status');
        });
        Route::namespace('Events')->group(function () {
            Route::get('events','EventsController@create')->name('events.create');
            Route::post('events-store','EventsController@store')->name('events.store');
            Route::get('events-list','EventsController@index')->name('events.list');
            Route::get('events/delete/{id}','EventsController@destroy')->name('events.destroy'); 
            Route::get('events/edit/{id}','EventsController@edit')->name('events.edit');
            Route::post('events/status/{id}', 'EventsController@status')->name('events.status');
        });
        Route::namespace('DigitalDirectory')->group(function () {
            Route::get('digitaldirectory','DigitalDirectoryController@create')->name('digitaldirectory.create');
            Route::post('digitaldirectory-store','DigitalDirectoryController@store')->name('digitaldirectory.store');
            Route::get('digitaldirectory-list','DigitalDirectoryController@index')->name('digitaldirectory.list');
            Route::get('digitaldirectory/delete/{id}','DigitalDirectoryController@destroy')->name('digitaldirectory.destroy'); 
            Route::get('digitaldirectory/edit/{id}','DigitalDirectoryController@edit')->name('digitaldirectory.edit');
            Route::post('digitaldirectory/status/{id}', 'DigitalDirectoryController@status')->name('digitaldirectory.status');
            Route::get('digitaldirectory/subcat/{id}','DigitalDirectoryController@getSubdigicategory')->name('getsubcatdigital');
            // None Listed Consultan
            Route::get('digitaldirectoryconsultant/list','ConsultantController@index')->name('digitaldirectory.none_listed_consultant');
            Route::get('digitaldirectoryconsultant/create','ConsultantController@create')->name('digitaldirectory.none_listed_consultant_create');
            Route::post('digitaldirectoryconsultant-store','ConsultantController@store')->name('digitaldirectory.none_listed_consultant_store');
            Route::get('digitaldirectoryconsultant/delete/{id}','ConsultantController@destroy')->name('digitaldirectory.none_listed_consultant_destroy'); 
            Route::get('digitaldirectoryconsultant/edit/{id}','ConsultantController@edit')->name('digitaldirectory.none_listed_consultant_edit');
            Route::post('digitaldirectoryconsultant/status/{id}', 'ConsultantController@status')->name('digitaldirectory.none_listed_consultant_status');
        });
        Route::namespace('Academys')->group(function(){
            // Author
            Route::get('author/list','AuthorController@index')->name('academys.list_author');
            Route::get('author/create','AuthorController@create')->name('academys.create_author');
            Route::get('author/edit/{id}','AuthorController@edit')->name('academys.edit_author');
            Route::get('author/delete/{id}','AuthorController@destroy')->name('academys.destroy_author');
            Route::post('author/store','AuthorController@store')->name('academys.store_author');
            //Route::post('academystore','AcademyController@create');

            //Contents
            Route::get('content/list','ContentController@index')->name('academys.list_content');
            Route::get('content/create','ContentController@create')->name('academys.create_content');
            Route::get('content/delete/{id}','ContentController@destroy')->name('academys.destroy_content');
            Route::get('content/edit/{id}','ContentController@edit')->name('academys.edit_content');
            Route::post('content/store','ContentController@store')->name('academys.store_content');

            //Webinar
            Route::get('webinar/list','WebinarController@index')->name('academys.list_webinar');
            Route::get('webinar/create','WebinarController@create')->name('academys.create_webinar');
            Route::get('webinar/edit/{id}','WebinarController@edit')->name('academys.edit_webinar');
            Route::get('webinar/delete/{id}','WebinarController@destroy')->name('academys.destroy_webinar');
            Route::post('webinar/store','WebinarController@store')->name('academys.store_webinar');

            //Articles
            Route::get('article/list','ArticleController@index')->name('academys.list_article');
            Route::get('article/create','ArticleController@create')->name('academys.create_article');
             Route::get('article/edit/{id}','ArticleController@edit')->name('academys.edit_article');
            Route::get('article/delete/{id}','ArticleController@destroy')->name('academys.destroy_article');
            Route::post('article/store','ArticleController@store')->name('academys.store_article');
        });
	});
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Front/DigitalDirectoryController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Country;
use App\Model\Front\Digitaldirectory;	
use App\Model\Front\Companytype;	
use App\Model\Front\Categories;
use DB;
use Carbon\Carbon;

class DigitalDirectoryController extends Controller
{
	public function index(Request $request){
		try {
			$directory_limit = 3;
			$page = trim($request->page);
			$directorys = DB::table('digital_directory')
							->select('digital_directory.*','categories.name as company_types','countries.country as countries_name')
							->leftjoin('categories','categories.id','digital_directory.company_type')
							->leftjoin('countries','countries.id','digital_directory.country')
							->where('categories.parent_id',35);
			if (count($request->all()) != 0) {
                if (isset($request->company_type) && !empty($request->company_type))
                {
                    $company_type = strip_tags(trim($request->company_type));
                    $directorys->where(function ($query) use ($company_type) {
                        $query->where('digital_directory.company_type', 'LIKE', '%' . $company_type . '%');
                    });
                }
                if (isset($request->country_name) && !empty($request->country_name))
                {
                    $country_name = strip_tags(trim($request->country_name));
                    $directorys->where(function ($query) use ($country_name) {
                        $query->where('digital_directory.country', 'LIKE', '%' . $country_name . '%');
                    });
                }

			}
			if($page!=""){
                $data['directorys'] = $directorys->paginate($directory_limit,['*'],'page',$page);
             }else{
                $data['directorys'] = $directorys->paginate($directory_limit);
            }
			$data['company_types'] = Categories::where('parent_id',35)->get();
			$data['countrys'] = Country::get();
			return view('web.digital_directory')->with($data);
		} catch (Exception $e) {
			log::error($e);
		}
	}
	public function WineUsa(Request $request){
		try {
			$data['directorys_usa'] = DB::table('digital_directory')
							->select('digital_directory.*','categories.name as company_types','countries.country as countries_name')
							->leftjoin('categories','categories.id','digital_directory.company_type')
							->leftjoin('countries','countries.id','digital_directory.country')
							->where('categories.parent_id',35)
							->where('digital_directory.non_listed_consultant','Yes')
							->paginate(3);
			return view('web.wine_importer_usa')->with($data);
		} catch (Exception $e) {
			log::error($e);
		}
	}
	public function wineDetail($id)
	{
		try{
			$data['wine_usa'] = Digitaldirectory::where('id',$id)->get();
			$data['company'] = Companytype::where('id',$id)->get();
			$data['countries'] = Country::where('id',$id)->get();
			return view('web.wine_importer_details')->with($data);
		} catch(Exception $e) {
			log::error($e);
		}
	}
	
}

resources/views/admin/digital_directory/list.blade.php
@extends('layouts.admin.layout')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Digital Directory</h4> </div>
		</div>
		@include('layouts.errors-and-messages')
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-listing">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<li><a href="{{ route('admin.digitaldirectory.create') }}">Add Digital Directory</a></li>
							<li class="active"><a>Digital Directory Listing</a></li>
					  	</ul>
					  
					  	<div class="tab-content">
							<div id="ProductListing" class="tab-pane fade in active">
								<div class="product-listing">
									<div class="table-responsive">
										<table id="events" class="events table border-b1px" style="width:100%">
											<thead>
												<tr>
													<th>Creation Date</th>
													<th>Edition Date</th>
													<th>Name</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody>
												@forelse ($digitaldirectorys as $digitaldirectory)
												<tr>
													<td>{{ date('d-m-Y',strtotime($digitaldirectory->created_at)) }}</td>
													<td>{{ date('d-m-Y',strtotime($digitaldirectory->updated_at)) }}</td>
													<td>{{$digitaldirectory->name}}</td>
													<td>

														<div class="action-btn">
															<form action="{{ route('admin.digitaldirectory.destroy', $digitaldirectory->id) }}" method="get" class="form-horizontal">
																{{ csrf_field() }}
																<input type="hidden" name="_method" value="delete">
																<div class="btn-group">
																	<a href="{{ route('admin.digitaldirectory.edit', $digitaldirectory->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
																	<button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
																</div>
															</form>
														</div>
													</td>
												</tr>
												@endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>
					  	</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection
<style type="text/css">
	.btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@push('js')
<script>
    $(document).ready(function() {
        init_datatable();
    } );
    
    function init_datatable(){
        $('#events').DataTable().destroy();
        setTimeout(function(){
            var table = $('#events').DataTable({
                deferRender: true,
                scrollX: true
            });
        },300);
    }
</script>
@endpush

resources/views/admin/digital_directory/non_listed_consultant.blade.php
@extends('layouts.admin.layout')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Digital Directory</h4> </div>
		</div>
		@include('layouts.errors-and-messages')
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-listing">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<li><a href="{{ route('admin.digitaldirectory.none_listed_consultant_create') }}">Add None Listed Consultant</a></li>
							<li class="active"><a>None Listed Consultant Listing</a></li>
					  	</ul>
					  
					  	<div class="tab-content">
							<div id="ProductListing" class="tab-pane fade in active">
								<div class="product-listing">
									<div class="table-responsive">
										<table id="events" class="events table border-b1px" style="width:100%">
											<thead>
												<tr>
													<th>Creation Date</th>
													<th>Edition Date</th>
													<th>Name</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody>
												@forelse ($digitaldirectorys_non_listed as $digitaldirectory)
												<tr>
													<td>{{ date('d-m-Y',strtotime($digitaldirectory->created_at)) }}</td>
													<td>{{ date('d-m-Y',strtotime($digitaldirectory->updated_at)) }}</td>
													<td>{{$digitaldirectory->name}}</td>
													<td>

														<div class="action-btn">
															<form action="{{ route('admin.digitaldirectory.none_listed_consultant_destroy', $digitaldirectory->id) }}" method="get" class="form-horizontal">
																{{ csrf_field() }}
																<input type="hidden" name="_method" value="delete">
																<div class="btn-group">
																	<a href="{{ route('admin.digitaldirectory.none_listed_consultant_edit', $digitaldirectory->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
																	<button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
																</div>
															</form>
														</div>
													</td>
												</tr>
												@endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>
					  	</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection
<style type="text/css">
	.btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@push('js')
<script>
    $(document).ready(function() {
        init_datatable();
    } );
    
    function init_datatable(){
        $('#events').DataTable().destroy();
        setTimeout(function(){
            var table = $('#events').DataTable({
                deferRender: true,
                scrollX: true
            });
        },300);
    }
</script>
@endpush