routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/* Web */
Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/search', 'HomeController@search')->name('home.search');


/* Front */ 
Route::namespace('Front')->group(function () {
    Route::get('front/login','LoginController@login')->name('front.login');
    Route::post('front/logindata','LoginController@logindata')->name('front.logindata');
    Route::get('front/logout','LoginController@logout')->name('front.logout');
    Route::get('front/profile','ProfileController@create')->name('front.profile');
    Route::get('front/create','RegisterController@create')->name('front.create');
    Route::post('front/store','RegisterController@store')->name('front.store');
	Route::get('/digital-directory', 'DigitalDirectoryController@index')->name('front.digitaldirectory');
	Route::get('/product/{id}', 'ProductController@index')->name('front.product_details');
    Route::get('/wine-importers-in-usa', 'DigitalDirectoryController@WineUsa')->name('front.wine_imports_usa');
    Route::get('/product-description/{id}','ProductController@view')->name('front.product_description');
    Route::get('/news-details/{id}','ProductController@newsDetail')->name('front.news_details');
    Route::get('/event-details/{id}','ProductController@eventDetail')->name('front.event_details');
    Route::get('/wine-importer-detail/{id}','DigitalDirectoryController@wineDetail')->name('front.wine_importer_details');
});
/* Buyer */

/* Seller */

/* Admin */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::namespace('Customers')->group(function () {
        	Route::resource('customers', 'CustomerController');
            Route::post('is_active/{id}','CustomerController@isActive')->name('customers.is_active');
       	});
		Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
        Route::namespace('Categories')->group(function () {
            Route::resource('categories', 'CategoryController');
            Route::get('categories/subcat/{id}','CategoryController@getSubcategory')->name('getsubcat');
        });
        Route::namespace('News')->group(function () {
            Route::get('news','NewsController@create')->name('news.create');
            Route::post('news-store','NewsController@store')->name('news.store');
            Route::get('news-list','NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','NewsController@edit')->name('news.edit');
            Route::post('news/status/{id}', 'NewsController@status')->name('news.status');
        });
        Route::namespace('Events')->group(function () {
            Route::get('events','EventsController@create')->name('events.create');
            Route::post('events-store','EventsController@store')->name('events.store');
            Route::get('events-list','EventsController@index')->name('events.list');
            Route::get('events/delete/{id}','EventsController@destroy')->name('events.destroy'); 
            Route::get('events/edit/{id}','EventsController@edit')->name('events.edit');
            Route::post('events/status/{id}', 'EventsController@status')->name('events.status');
        });
        Route::namespace('DigitalDirectory')->group(function () {
            Route::get('digitaldirectory','DigitalDirectoryController@create')->name('digitaldirectory.create');
            Route::post('digitaldirectory-store','DigitalDirectoryController@store')->name('digitaldirectory.store');
            Route::get('digitaldirectory-list','DigitalDirectoryController@index')->name('digitaldirectory.list');
            Route::get('digitaldirectory/delete/{id}','DigitalDirectoryController@destroy')->name('digitaldirectory.destroy'); 
            Route::get('digitaldirectory/edit/{id}','DigitalDirectoryController@edit')->name('digitaldirectory.edit');
            Route::post('digitaldirectory/status/{id}', 'DigitalDirectoryController@status')->name('digitaldirectory.status');
            Route::get('digitaldirectory/subcat/{id}','DigitalDirectoryController@getSubdigicategory')->name('getsubcatdigital');
            // None Listed Consultan
            Route::get('digitaldirectoryconsultant/list','ConsultantController@index')->name('digitaldirectory.none_listed_consultant');
            Route::get('digitaldirectoryconsultant/create','ConsultantController@create')->name('digitaldirectory.none_listed_consultant_create');
            Route::post('digitaldirectoryconsultant-store','ConsultantController@store')->name('digitaldirectory.none_listed_consultant_store');
            Route::get('digitaldirectoryconsultant/delete/{id}','ConsultantController@destroy')->name('digitaldirectory.none_listed_consultant_destroy'); 
            Route::get('digitaldirectoryconsultant/edit/{id}','ConsultantController@edit')->name('digitaldirectory.none_listed_consultant_edit');
            Route::post('digitaldirectoryconsultant/status/{id}', 'ConsultantController@status')->name('digitaldirectory.none_listed_consultant_status');
        });
        Route::namespace('Academys')->group(function(){
            // Author
            Route::get('author/list','AuthorController@index')->name('academys.list_author');
            Route::get('author/create','AuthorController@create')->name('academys.create_author');
            Route::get('author/edit/{id}','AuthorController@edit')->name('academys.edit_author');
            Route::get('author/delete/{id}','AuthorController@destroy')->name('academys.destroy_author');
            Route::post('author/store','AuthorController@store')->name('academys.store_author');
            //Route::post('academystore','AcademyController@create');

            //Contents
            Route::get('content/list','ContentController@index')->name('academys.list_content');
            Route::get('content/create','ContentController@create')->name('academys.create_content');
            Route::get('content/delete/{id}','ContentController@destroy')->name('academys.destroy_content');
            Route::get('content/edit/{id}','ContentController@edit')->name('academys.edit_content');
            Route::post('content/store','ContentController@store')->name('academys.store_content');

            //Webinar
            Route::get('webinar/list','WebinarController@index')->name('academys.list_webinar');
            Route::get('webinar/create','WebinarController@create')->name('academys.create_webinar');
            Route::get('webinar/edit/{id}','WebinarController@edit')->name('academys.edit_webinar');
            Route::get('webinar/delete/{id}','WebinarController@destroy')->name('academys.destroy_webinar');
            Route::post('webinar/store','WebinarController@store')->name('academys.store_webinar');

            //Articles
            Route::get('article/list','ArticleController@index')->name('academys.list_article');
            Route::get('article/create','ArticleController@create')->name('academys.create_article');
             Route::get('article/edit/{id}','ArticleController@edit')->name('academys.edit_article');
            Route::get('article/delete/{id}','ArticleController@destroy')->name('academys.destroy_article');
            Route::post('article/store','ArticleController@store')->name('academys.store_article');
        });
	});
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/breadcumb.blade.php
<section class="content-header">
    <h1>
        Dashboard
        <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
        @foreach($breadcumbs as $breadcumb)
            @if($loop->last)
                <li><a href="#" class="active">@if(isset($breadcumb["icon"]))<i
                                class="{{$breadcumb["icon"]}}"></i> @endif {{$breadcumb["name"]}}</a></li>
            @else
                <li><a href="{{ $breadcumb["url"] }}">@if(isset($breadcumb["icon"]))<i
                                class="{{$breadcumb["icon"]}}"></i> @endif {{$breadcumb["name"]}}</a></li>
            @endif
        @endforeach
    </ol>
</section>

resources/views/layouts/admin/footer.blade.php
<footer class="footer text-center">{{date('Y')}} &copy; The World-beverages. All Rights Reserved. </footer>

resources/views/layouts/admin/header.blade.php
<!-- Topbar header - style you can find in pages.scss -->
<nav class="navbar navbar-default navbar-static-top m-b-0">
	<div class="navbar-header">
		<div class="top-left-part">
			<!-- Logo -->
				<a href="{{route('admin.dashboard')}}" class="logo">
				<img class="logofull" src="{{ url('img/icon/logo1.png') }}" alt="home" />
				<img class="logosmall" src="{{ url('img/icon/logo-admin.png') }}" alt="home" />
			  </a>
		</div>
		<!-- /Logo -->
		<!-- Search input and Toggle icon -->
		<ul class="nav navbar-top-links navbar-left">
			
			<li><a href="javascript:void(0)" class="open-close waves-effect waves-light"><i class="ti-menu"></i></a></li>
			<li>
				<form role="search" class="app-search hidden-sm hidden-xs m-r-10">
					<input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a> </form>
			</li>
		   
		</ul>
		<ul class="nav navbar-top-links navbar-right pull-right clr-icn">
				<li class="dropdown">
						
						<ul class="dropdown-menu mailbox animated bounceInDown">
							<li>
								<div class="drop-title">You have 4 new messages</div>
							</li>
							<li>
								<div class="message-center">
									<a href="#">
										<div class="user-img"> <img src="{{ asset('assets/plugins/images/users/pawandeep.jpg') }}" alt="user" class="img-circle"> <span class="profile-status online pull-right"></span> </div>
										<div class="mail-contnet">
											<h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </div>
									</a>
									<a href="#">
										<div class="user-img"> <img src="{{ asset('assets/plugins/images/users/sonu.jpg') }}" alt="user" class="img-circle"> <span class="profile-status busy pull-right"></span> </div>
										<div class="mail-contnet">
											<h5>Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </div>
									</a>
									<a href="#">
										<div class="user-img"> <img src="{{ asset('assets/plugins/images/users/arijit.jpg') }}" alt="user" class="img-circle"> <span class="profile-status away pull-right"></span> </div>
										<div class="mail-contnet">
											<h5>Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </div>
									</a>
									<a href="#">
										<div class="user-img"> <img src="{{ asset('assets/plugins/images/users/pawandeep.jpg') }}" alt="user" class="img-circle"> <span class="profile-status offline pull-right"></span> </div>
										<div class="mail-contnet">
											<h5>Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </div>
									</a>
								</div>
							</li>
							<li>
								<a class="text-center" href="javascript:void(0);"> <strong>See all notifications</strong> <i class="fa fa-angle-right"></i> </a>
							</li>
						</ul>
						<!-- /.dropdown-messages -->
					</li>
			<li class="dropdown">
				<a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#">
					
        		<img src="#" alt="user-img" width="36" height="36" class="img-circle">
        	
					<b class="hidden-xs">
					</b><span class="caret"></span> </a>
				<ul class="dropdown-menu dropdown-user animated flipInY">
					<li>
						<div class="dw-user-box">
							<div class="u-img">
			        		<img src="" alt="user">
			        	
							</div>
							<div class="u-text">
								<h4></h4>
								<p class="text-muted"></p><a href="#" class="btn btn-rounded btn-danger btn-sm">View Profile</a></div>
						</div>
					</li>
					<li role="separator" class="divider"></li>
					<li><a href="#"><i class="ti-user"></i> My Profile</a></li>
					<li><a href="#"><i class="ti-wallet"></i> My Balance</a></li>
					<li><a href="#"><i class="ti-email"></i> Inbox</a></li>
					<li role="separator" class="divider"></li>
					<li><a href="#"><i class="ti-settings"></i> Account Setting</a></li>
					<li role="separator" class="divider"></li>
					<li><a href="{{ route('admin.logout') }}"><i class="fa fa-power-off"></i> Logout</a></li>
				</ul>
				<!-- /.dropdown-user -->
			</li>
			<!-- /.dropdown -->
		</ul>
	</div>
	<!-- /.navbar-header -->
	<!-- /.navbar-top-links -->
	<!-- /.navbar-static-side -->
</nav>
<!-- End Top Navigation -->

resources/views/layouts/admin/login_layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url('img/icon/favicon.png') }}">

    <title>@yield('title')</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{ url('admin/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url('admin/css/themify-icons.css') }}" rel="stylesheet">
   
   
    <link href="{{ url('admin/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{{ url('admin/css/animate.css') }}" rel="stylesheet">
    <!-- Custom CSS -->
    
    <link href="{{ url('admin/css/login.css') }}" rel="stylesheet">
    <link href="{{ url('admin/css/style.css') }}" rel="stylesheet">
    <link href="{{ url('admin/css/default.cs') }}s" rel="stylesheet">
    
    <link href="{{ url('admin/css/custom.cs') }}s" rel="stylesheet">
    <link href="{{ url('admin/css/responsive.css') }}" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,600,700" rel="stylesheet">
    @stack('css')
</head>

<body>
    @yield('content')
</body>
<!-- All Jquery -->
    <script src="{{ url('admin/plugins/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{{ url('admin/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ url('admin/js/admin.min.js') }}"></script>   
    @stack('script') 
</html>

resources/views/layouts/admin/sidebar.blade.php
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<div class="navbar-default sidebar" role="navigation">
	<div class="sidebar-nav slimscrollsidebar">
		<div class="sidebar-head">
			<h3><span class="fa-fw open-close"><i class="ti-close ti-menu"></i></span> <span class="hide-menu">Navigation</span></h3> </div>
		
		<ul class="nav" id="side-menu">
			<li class="sidebar-item @if(Request::route()->getName() == 'admin.dashboard') active @endif">
				<a href="{{ route('admin.dashboard') }}" class="sidebar-link has-arrow waves-effect has-error">
					<span class="hide-menu">Dashboard</span>
				</a>
		 	</li>
		 	<li class="sidebar-item @if(request()->segment(2) == 'customers' || request()->segment(2) == 'addresses' || Request::route()->getName() == 'admin.customers.search') active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage User</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.customers.index') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.customers.index' || Request::route()->getName() == 'admin.customers.search') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">User Listing</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.customers.create') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.customers.create') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">User Create </span>
						</a>
					</li>
					
				</ul>
			</li>
			<li class="sidebar-item @if(request()->segment(2) == 'products' || Request::route()->getName() == 'admin.products.search' ) active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage Products</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.products.index') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.products.index' || Request::route()->getName() == 'admin.products.search' ) active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Product Listing</span>
						</a>
					</li>
					
					<li class="sidebar-item">
						<a href="{{ route('admin.products.create') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.products.create' || Request::route()->getName() == 'admin.products.edit') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Add Procucts</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="sidebar-item @if(request()->segment(2) == 'categories' || Request::route()->getName() == 'admin.categories.search') active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage Categories</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.categories.index') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.categories.index' || Request::route()->getName() == 'admin.categories.search') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List categories</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.categories.create') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.categories.create' || Request::route()->getName() == 'admin.categories.edit') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create category</span>
						</a>
					</li>
				</ul>
		 	</li>
		 	<li class="sidebar-item @if(request()->segment(2) == 'news' || Request::route()->getName() == 'admin.news.list' || Request::route()->getName() == 'admin.news.search' ) active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage News</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.news.list') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.news.list' || Request::route()->getName() == 'admin.news.search' ) active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List news</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.news.create') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.news.create' || Request::route()->getName() == 'admin.news.edit') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create news</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="sidebar-item @if(request()->segment(2) == 'events' || Request::route()->getName() == 'admin.events.list' || Request::route()->getName() == 'admin.events.search' ) active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage Events</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.events.list') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.events.list') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List Events</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.events.create') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.events.create' || Request::route()->getName() == 'admin.events.edit') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create Events</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="sidebar-item @if(request()->segment(2) == 'digitaldirectory' || Request::route()->getName() == 'admin.digitaldirectory.list'||Request::route()->getName() =='admin.digitaldirectory.none_listed_consultant') active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage Digital Directory</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.digitaldirectory.list') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.digitaldirectory.list') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List Digital Directory</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.digitaldirectory.create') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.digitaldirectory.create' || Request::route()->getName() == 'admin.digitaldirectory.edit') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create Digital Directory</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.digitaldirectory.none_listed_consultant') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.digitaldirectory.none_listed_consultant') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">None listed Consultant</span>
						</a>
					</li>
				</ul>
			</li>
			<li class="sidebar-item @if(request()->segment(2) == 'academy' || Request::route()->getName() == 'admin.academys.list_author'||Request::route()->getName() =='admin.academys.create_author' || Request::route()->getName() == 'admin.academys.edit_author' || Request::route()->getName() == 'admin.academys.create_content' || Request::route()->getName() == 'admin.academys.list_content' || Request::route()->getName() == 'admin.academys.edit_content' || Request::route()->getName() == 'admin.academys.list_webinar' || Request::route()->getName() == 'admin.academys.create_webinar' || Request::route()->getName() == 'admin.academys.edit_webinar' || Request::route()->getName() == 'admin.academys.list_article' || Request::route()->getName() == 'admin.academys.create_article' || Request::route()->getName() == 'admin.academys.edit_article') active @endif">
				<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
					<span class="hide-menu">Manage Academy</span>
				</a>
				<ul aria-expanded="false" class="collapse first-level">
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.create_webinar') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.create_webinar' || Request::route()->getName() == 'admin.academys.edit_webinar') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create Webinars</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.list_webinar') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.list_webinar') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List Webinars</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.create_author') }}"  class="sidebar-link @if(Request::route()->getName() == 'admin.academys.create_author' || Request::route()->getName() == 'admin.academys.edit_author') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create Authors</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.list_author') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.list_author') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List Authors</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.create_content') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.create_content' || Request::route()->getName() == 'admin.academys.edit_content') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create Contents</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.list_content') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.list_content') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List Contents</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.create_article') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.create_article' || Request::route()->getName() == 'admin.academys.edit_article') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">Create Articles</span>
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route('admin.academys.list_article') }}" class="sidebar-link @if(Request::route()->getName() == 'admin.academys.list_article') active @endif">
							<i class="mdi mdi-adjust"></i>
							<span class="hide-menu">List Articles</span>
						</a>
					</li>
				</ul>
			</li>
		</ul>
	</div>
</div>