routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/* Web */
Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/search', 'HomeController@search')->name('home.search');


/* Front */ 
Route::namespace('Front')->group(function () {
    Route::get('front/login','LoginController@login')->name('front.login');
    Route::post('front/logindata','LoginController@logindata')->name('front.logindata');
    Route::get('front/logout','LoginController@logout')->name('front.logout');
    Route::get('front/profile','ProfileController@create')->name('front.profile');
    Route::get('front/create','RegisterController@create')->name('front.create');
    Route::post('front/store','RegisterController@store')->name('front.store');
	Route::get('/digital-directory', 'DigitalDirectoryController@index')->name('front.digitaldirectory');
	Route::get('/product/{id}', 'ProductController@index')->name('front.product_details');
    Route::get('/wine-importers-in-usa', 'DigitalDirectoryController@WineUsa')->name('front.wine_imports_usa');
    Route::get('/product-description/{id}','ProductController@view')->name('front.product_description');
    Route::get('/news-details/{id}','ProductController@newsDetail')->name('front.news_details');
    Route::get('/event-details/{id}','ProductController@eventDetail')->name('front.event_details');
    Route::get('/wine-importer-detail/{id}','DigitalDirectoryController@wineDetail')->name('front.wine_importer_details');
});
/* Buyer */

/* Seller */

/* Admin */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
		Route::get('dashboard', 'DashboardController@index')->name('dashboard');
		Route::namespace('Customers')->group(function () {
        	Route::resource('customers', 'CustomerController');
            Route::post('is_active/{id}','CustomerController@isActive')->name('customers.is_active');
       	});
		Route::namespace('Products')->group(function () {
            Route::resource('products', 'ProductController');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
        Route::namespace('Categories')->group(function () {
            Route::resource('categories', 'CategoryController');
            Route::get('categories/subcat/{id}','CategoryController@getSubcategory')->name('getsubcat');
        });
        Route::namespace('News')->group(function () {
            Route::get('news','NewsController@create')->name('news.create');
            Route::post('news-store','NewsController@store')->name('news.store');
            Route::get('news-list','NewsController@index')->name('news.list');
            Route::get('news/delete/{id}','NewsController@destroy')->name('news.destroy'); 
            Route::get('news/edit/{id}','NewsController@edit')->name('news.edit');
            Route::post('news/status/{id}', 'NewsController@status')->name('news.status');
        });
        Route::namespace('Events')->group(function () {
            Route::get('events','EventsController@create')->name('events.create');
            Route::post('events-store','EventsController@store')->name('events.store');
            Route::get('events-list','EventsController@index')->name('events.list');
            Route::get('events/delete/{id}','EventsController@destroy')->name('events.destroy'); 
            Route::get('events/edit/{id}','EventsController@edit')->name('events.edit');
            Route::post('events/status/{id}', 'EventsController@status')->name('events.status');
        });
        Route::namespace('DigitalDirectory')->group(function () {
            Route::get('digitaldirectory','DigitalDirectoryController@create')->name('digitaldirectory.create');
            Route::post('digitaldirectory-store','DigitalDirectoryController@store')->name('digitaldirectory.store');
            Route::get('digitaldirectory-list','DigitalDirectoryController@index')->name('digitaldirectory.list');
            Route::get('digitaldirectory/delete/{id}','DigitalDirectoryController@destroy')->name('digitaldirectory.destroy'); 
            Route::get('digitaldirectory/edit/{id}','DigitalDirectoryController@edit')->name('digitaldirectory.edit');
            Route::post('digitaldirectory/status/{id}', 'DigitalDirectoryController@status')->name('digitaldirectory.status');
            Route::get('digitaldirectory/subcat/{id}','DigitalDirectoryController@getSubdigicategory')->name('getsubcatdigital');
            // None Listed Consultan
            Route::get('digitaldirectoryconsultant/list','ConsultantController@index')->name('digitaldirectory.none_listed_consultant');
            Route::get('digitaldirectoryconsultant/create','ConsultantController@create')->name('digitaldirectory.none_listed_consultant_create');
            Route::post('digitaldirectoryconsultant-store','ConsultantController@store')->name('digitaldirectory.none_listed_consultant_store');
            Route::get('digitaldirectoryconsultant/delete/{id}','ConsultantController@destroy')->name('digitaldirectory.none_listed_consultant_destroy'); 
            Route::get('digitaldirectoryconsultant/edit/{id}','ConsultantController@edit')->name('digitaldirectory.none_listed_consultant_edit');
            Route::post('digitaldirectoryconsultant/status/{id}', 'ConsultantController@status')->name('digitaldirectory.none_listed_consultant_status');
        });
        Route::namespace('Academys')->group(function(){
            // Author
            Route::get('author/list','AuthorController@index')->name('academys.list_author');
            Route::get('author/create','AuthorController@create')->name('academys.create_author');
            Route::get('author/edit/{id}','AuthorController@edit')->name('academys.edit_author');
            Route::get('author/delete/{id}','AuthorController@destroy')->name('academys.destroy_author');
            Route::post('author/store','AuthorController@store')->name('academys.store_author');
            //Route::post('academystore','AcademyController@create');

            //Contents
            Route::get('content/list','ContentController@index')->name('academys.list_content');
            Route::get('content/create','ContentController@create')->name('academys.create_content');
            Route::get('content/delete/{id}','ContentController@destroy')->name('academys.destroy_content');
            Route::get('content/edit/{id}','ContentController@edit')->name('academys.edit_content');
            Route::post('content/store','ContentController@store')->name('academys.store_content');

            //Webinar
            Route::get('webinar/list','WebinarController@index')->name('academys.list_webinar');
            Route::get('webinar/create','WebinarController@create')->name('academys.create_webinar');
            Route::get('webinar/edit/{id}','WebinarController@edit')->name('academys.edit_webinar');
            Route::get('webinar/delete/{id}','WebinarController@destroy')->name('academys.destroy_webinar');
            Route::post('webinar/store','WebinarController@store')->name('academys.store_webinar');

            //Articles
            Route::get('article/list','ArticleController@index')->name('academys.list_article');
            Route::get('article/create','ArticleController@create')->name('academys.create_article');
             Route::get('article/edit/{id}','ArticleController@edit')->name('academys.edit_article');
            Route::get('article/delete/{id}','ArticleController@destroy')->name('academys.destroy_article');
            Route::post('article/store','ArticleController@store')->name('academys.store_article');
        });
	});
});

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/Categories/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Categories;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Front\Categories;
use Validator;
use Auth;
use Log;

class CategoryController extends Controller
{
    public function index(Request $request)
    {
        try{
            $data['categories'] = Categories::get();
            return view('admin.categories.list')->with($data);
        }
        catch (Exception $e) {
            log::error($e);
        }
    }
    public function create()
    {
        try{
            $data['category_availabilitys'] = Categories::orderBy('id','desc')->where('subcat_id',null)->where('parent_id',null)->get();
            return view('admin.categories.create')->with($data);
        }
        catch (Exception $e) {
            log::error($e);
        }
    }
    public function store(Request $request)
    {
        try{
            $rules =[
                'name' => 'required|string|max:255',
            ];
            $customeMessage = [
                'name.required' => 'Please enter name.',
            ];
            $validator = Validator::make($request->all(),$rules,$customeMessage);
            if( $validator->fails() ){
                return back()->withInput()->withErrors($validator->errors());
            } else{ 
                $id = trim(strip_tags($request->id)); 
                $name = trim(strip_tags($request->name));
                $category_availability = trim(strip_tags($request->category_availability));
                $subcat_id = trim(strip_tags($request->subcat_id));
                if($id!=""){
                    $category=Categories::find($id);
                }else{
                    $category=New Categories();
                }
                if ($category_availability!="") {
                    $category->parent_id = $category_availability;
                }
                if ($subcat_id!="") {
                    $category->subcat_id = $subcat_id;
                }
                $category->name = $name;
                $category->save();
            }
            if($request->id!=""){    
                return redirect()->route('admin.categories.index')->with('message', 'Category Update Succesfully.');
            }
            else{
                return redirect()->route('admin.categories.index')->with('message', 'Category Create Succesfully.');
            }
        }
        catch (Exception $e) {
            log::error($e);
        }
    }
    public function edit($id)
    {
        try{
            if(Categories::where('id',$id)->exists()){  
                $data['category_availabilitys'] = Categories::orderBy('id','desc')->where('subcat_id',null)->where('parent_id',null)->get();
                $data['category'] = Categories::where('id',$id)->first();
                $data['parent_id'] = Categories::where('id',$data['category']->parent_id)->first();                
                return view('admin.categories.create')->with($data);    
            }
        }
        catch(\Exception $e){
            $Exceptions = New Exceptions;
            $Exceptions->sendException($e);  
        }
    }
    public function destroy(int $id)
    {
        try{
            if (Categories::where('id',$id)->exists()) {
                $cat_delete = Categories::where('id',$id)->delete();
                return redirect()->route('admin.categories.index')->with('message', 'Category delete successfully.');
            }
        }
        catch (Exception $e) {
            Exceptions::exception($e);
        }
    }
    public function getSubcategory($id){
        try {
            $subcat_id = Categories::where('parent_id',$id)->where('subcat_id',null)->pluck('id','name');
            return $subcat_id;
        } catch (Exception $e) {
            Log::error($e);
        }
    }
}

    

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.layout')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Categories</h4> </div>
			<!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="#">Manage Products</a></li>
					<li class="active">Add Products</li>
				</ol>
			</div> -->
			<!-- /.col-lg-12 -->
		</div>
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					
					<div class="product-tab">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							@if(isset($category->id))
								<li class="active"><a>Edit Category</a></li>
							@else
								<li class="active"><a>Add Category</a></li>
							@endif
							<li><a href="{{ route('admin.categories.index') }}">Categories Listing</a></li>
					  </ul>
					  <div class="tab-content">
							<div id="AddProcucts" class="tab-pane fade in active">
								<div class="add-product">
								  <form action="{{ route('admin.categories.store') }}" method="post" class="form" enctype="multipart/form-data">
									@csrf
		                			@if(isset($category->id))
				            			<input type="hidden" name="id" id="id" value="{{$category->id}}">
		            				@else
				            			<input type="hidden" name="id" value="">
			            			@endif
									<div class="row">
										<div class="col-sm-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label>Category Availability</label>
												<select name="category_availability" class="form-control" id="category_availability">
													<option value="">None</option>
													@foreach($category_availabilitys as $category_availability)
													<option value="{{$category_availability->id}} "@if(old('category_availability')==$category_availability->id) selected="true" @elseif(isset($parent_id->id) && $parent_id->id==$category_availability->id)selected="true" @endif>{{$category_availability->name}}</option>
													@endforeach
												</select>
												<input type="hidden" name="selected_parent" id="selected_parent" value="@if(isset($category->parent_id)){{ $category->parent_id }}@elseif(old('selected_parent')!=''){{ old('selected_parent') }} @endif">
												@if($errors->has('category_availability'))
	                                      			<span class="text-danger">{{$errors->first('category_availability')}}</span>
	                                    		@endif
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label>Parent Category</label>
												<select name="subcat_id" class="form-control" id="subcat_id">
													<option value="">None</option>
												</select>
												<input type="hidden" name="selected_subcat" id="selected_subcat" value="@if(isset($category->subcat_id)){{ $category->subcat_id }}@elseif(old('selected_subcat')!=''){{ old('selected_subcat') }} @endif">
												@if($errors->has('subcat_id'))
	                                      			<span class="text-danger">{{$errors->first('subcat_id')}}</span>
	                                    		@endif
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-6 col-md-6 col-sm-6 col-xs-12">
											<div class="form-group">
												<label>Name<span class="red">*</span></label>
												<input type="text" class="form-control" name="name" id="name" value="@if(isset($category->name)){{$category->name}}@elseif(old('name')!=''){{old('name')}} @endif" maxlength="50" placeholder="Enter Category Name">
												@if($errors->has('name'))
	                                      			<span class="text-danger">{{$errors->first('name')}}</span>
	                                    		@endif
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-sm-12">
											<div class="submit-btn">
												<button type="submit" class="btn btn-submit">Submit</button>
											</div>
										</div>
									</div>
								</form>
							</div>
					  	</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection
@push('js')
<script type="text/javascript">
$(document).ready(function() {
	$('#cover').bind('change', function () {
		var filename = $("#cover").val();
		if (/^\s*$/.test(filename)) {
			$(".file-upload").find('#cover').removeClass('active');
			$("#noFile").text("No file chosen...");
		}
		else {
			$(".file-upload").find('#cover').addClass('active');
			$("#noFile").text(filename.replace("C:\\fakepath\\", ""));
		}
	});
	$("#category_availability").on('change',function($e){
		category_availability = $("#category_availability").val();
		getSubcat(category_availability);
		console.log(category_availability);
	});
	if($("#selected_parent").val()!=""){
		selected_parent = $("#selected_parent").val();
		getSubcat(selected_parent);
	};
	if($("#selected_subcat").val()!=""){
		selected_subcat = $("#selected_subcat").val();
	};
});
function getSubcat(id){
	$.ajax({
        type : "GET",
        url : "{{ url('admin/categories/subcat/') }}/"+id,
        success : function(response){
        	$('#subcat_id').empty();
            $('#subcat_id').append('<option value="">None</option>');
            $.each(response, function(key, value){
                if(selected_subcat==value){
                	if (id!=value) {
						$('#subcat_id').append('<option value="'+ value +'" selected="true">' + key + '</option>');
                	}
                }
             	else{
             		id = $("#id").val();
                 	if (id!=value) {
                    	$('#subcat_id').append('<option value="'+ value +'">' + key + '</option>');
                	}
                }
            });
    	},
    	error: function(error){
        	console.log(error);
        }
    });	
}
</script>
@endpush

resources/views/admin/categories/list.blade.php
@extends('layouts.admin.layout')
@section('content')
	<div class="container-fluid">
		<div class="row bg-title">
			<div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
				<h4 class="page-title">Manage Categories</h4> </div>
			<!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
				<ol class="breadcrumb">
					<li><a href="#">Manage Products</a></li>
					<li class="active">Add Products</li>
				</ol>
			</div> -->
			<!-- /.col-lg-12 -->
		</div>
		@include('layouts.errors-and-messages')
		@if($categories)
		<div class="page-content">
			<div class="row">
				<div class="col-sm-12">
					<div class="product-listing">
						<ul class="nav nav-tabs" data-spy="affix" data-offset-top="135">
							<li><a href="{{ route('admin.categories.create') }}">Add Category</a></li>
							<li class="active"><a>Categories Listing</a></li>
					  </ul>
					  <div class="tab-content">
							<div id="ProductListing" class="tab-pane fade in active">
								<div class="product-listing">
									<div class="table-responsive">
										<table id="categories" class="table border-b1px" style="width:100%">
											<thead>
												<tr>
													<th>Name</th>
													<th>Actions</th>
												</tr>
											</thead>
											<tbody>
											@forelse ($categories as $category)
												<tr>
													<td>{{ $category->name }}</td>
													<td>
														<div class="action-btn">
															<form action="{{ route('admin.categories.destroy', $category->id) }}" method="post" class="form-horizontal">
																{{ csrf_field() }}
																<input type="hidden" name="_method" value="delete">
																<div class="btn-group">
																	<a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-edit"><i class="mdi mdi-pencil"></i></a>
																	<button onclick="return confirm('Are you sure you want to delete?')" type="submit" class="btn btn-delete"><i class="mdi mdi-close"></i></button>
																</div>
															</form>
														</div>
													</td>
												</tr>
											@empty
												<tr>
													<td colspan="3" align="center">Data Not Found</td>
												</tr>
											@endforelse
											</tbody>
										</table>
								</div>
							</div>
						</div>
				  	</div>
				</div>
			</div>
		</div>
	</div>
	@endif
</div>
@endsection
<style type="text/css">
	.btn-info, .btn-info.disabled {
        color: black!important;
        background: #e4e7ea!important;
    }
    .btn-info:hover{
        border:1px solid!important;
        border-color: none!important;
    }
</style>
@push('js')
<script>
	$(document).ready(function() {
		$('#categories').DataTable();
	} );
</script>
@endpush